[package]
name = "hab"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "../build-habitat.rs"
workspace = "../../"

[[bin]]
name = "hab"
doc = false

[dependencies]
# Can we keep these alphabetized? We're not savages.
atty = "*"
base64 = "*"
bitflags = "*"
chrono = {version = "*", features = ["serde"]}
dirs = "*"
env_logger = "*"
flate2 = "*"
futures = { version = "*" }
glob = "*"
habitat_api_client = { path = "../builder-api-client" }
habitat_common = { path = "../common" }
habitat_core = { path = "../core" }
habitat-sup-client = { path = "../sup-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "0.29.1", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
pbr = "*"
rants = "*"
reqwest = { version = "*", features = ["blocking", "json"] }
retry = "*"
same-file = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
structopt = "*"
tabwriter = "*"
tar = "*"
termcolor = "*"
tokio = { version = "*", features = ["full"] }
toml = { version = "*", default-features = false }
url = "*"
walkdir = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.uuid]
version = "*"
features = ["v4"]

[target.'cfg(windows)'.dependencies]
widestring = "*"
winapi = { version = "*", features = ["winuser", "windef"] }
winreg = "*"

[dev-dependencies]
tempfile = "*"

[features]
default = ["supported_targets"]
functional = []
supported_targets = ["habitat_core/supported_targets"]
aarch64-linux = ["habitat_core/aarch64-linux"]
